-- Datos de ejemplo para empresas en convenio
-- Este archivo inserta empresas de ejemplo marcadas como destacadas

USE claut_intranet;

-- Insertar empresas de ejemplo
INSERT INTO empresas_convenio (
    nombre_empresa, 
    descripcion, 
    logo_url, 
    sitio_web, 
    telefono, 
    email, 
    direccion, 
    categoria, 
    descuento, 
    beneficios, 
    fecha_inicio_convenio, 
    fecha_fin_convenio, 
    activo, 
    destacado
) VALUES 
(
    'TechSolutions Mexico',
    'Empresa líder en soluciones tecnológicas y desarrollo de software para el sector automotriz.',
    'https://ui-avatars.com/api/?name=TechSolutions&background=0080ff&color=fff&size=128',
    'https://techsolutions.mx',
    '+52 55 1234 5678',
    'contacto@techsolutions.mx',
    'Av. Tecnológico 1234, CDMX',
    'Tecnología',
    15.0,
    '15% de descuento en todos los servicios de desarrollo y consultoría tecnológica',
    '2024-01-15',
    '2025-12-31',
    1,
    1
),
(
    'AutoServicios Premium',
    'Centro de servicios automotrices especializado en mantenimiento y reparación de vehículos.',
    'https://ui-avatars.com/api/?name=AutoServicios&background=ff6b35&color=fff&size=128',
    'https://autoservicios.com.mx',
    '+52 55 2345 6789',
    'info@autoservicios.com.mx',
    'Blvd. Automotriz 567, Estado de México',
    'Automotriz',
    20.0,
    '20% de descuento en servicios de mantenimiento preventivo y correctivo',
    '2024-02-01',
    '2025-12-31',
    1,
    1
),
(
    'Capacitación Industrial Plus',
    'Instituto especializado en capacitación y desarrollo de habilidades para la industria manufacturera.',
    'https://ui-avatars.com/api/?name=Capacitacion&background=28a745&color=fff&size=128',
    'https://capacitacionplus.edu.mx',
    '+52 55 3456 7890',
    'cursos@capacitacionplus.edu.mx',
    'Zona Industrial Norte, Tlalnepantla',
    'Educación',
    25.0,
    '25% de descuento en cursos de certificación y diplomados especializados',
    '2024-01-10',
    '2025-12-31',
    1,
    1
),
(
    'Logística Global Express',
    'Empresa de logística y transporte especializada en la cadena de suministro automotriz.',
    'https://ui-avatars.com/api/?name=Logistica&background=6c757d&color=fff&size=128',
    'https://logisticaglobal.mx',
    '+52 55 4567 8901',
    'servicios@logisticaglobal.mx',
    'Parque Industrial Cuautitlán',
    'Logística',
    12.0,
    '12% de descuento en servicios de transporte y almacenamiento',
    '2024-03-01',
    '2025-12-31',
    1,
    1
),
(
    'Salud Corporativa Integral',
    'Centro médico especializado en medicina ocupacional y servicios de salud para empresas.',
    'https://ui-avatars.com/api/?name=Salud&background=dc3545&color=fff&size=128',
    'https://saludcorporativa.mx',
    '+52 55 5678 9012',
    'citas@saludcorporativa.mx',
    'Medical Center Plaza, Satélite',
    'Salud',
    18.0,
    '18% de descuento en consultas médicas, exámenes ocupacionales y estudios de laboratorio',
    '2024-01-20',
    '2025-12-31',
    1,
    1
),
(
    'Equipos y Herramientas Industriales',
    'Proveedor especializado en equipos, herramientas y maquinaria para la industria automotriz.',
    'https://ui-avatars.com/api/?name=Equipos&background=6f42c1&color=fff&size=128',
    'https://equiposindustriales.mx',
    '+52 55 6789 0123',
    'ventas@equiposindustriales.mx',
    'Corredor Industrial Toluca',
    'Manufactura',
    10.0,
    '10% de descuento en compra de equipos y herramientas especializadas',
    '2024-02-15',
    '2025-12-31',
    1,
    1
),
(
    'Consultoría Empresarial Avanzada',
    'Firma de consultoría especializada en optimización de procesos y gestión de calidad.',
    'https://ui-avatars.com/api/?name=Consultoria&background=fd7e14&color=fff&size=128',
    'https://consultoriaavanzada.mx',
    '+52 55 7890 1234',
    'consultores@consultoriaavanzada.mx',
    'Torre Corporativa Santa Fe',
    'Servicios',
    22.0,
    '22% de descuento en servicios de consultoría y auditorías de procesos',
    '2024-01-05',
    '2025-12-31',
    1,
    1
),
(
    'Seguridad Industrial Total',
    'Empresa especializada en sistemas de seguridad industrial y equipos de protección personal.',
    'https://ui-avatars.com/api/?name=Seguridad&background=e83e8c&color=fff&size=128',
    'https://seguridadtotal.mx',
    '+52 55 8901 2345',
    'seguridad@seguridadtotal.mx',
    'Parque Industrial Ecatepec',
    'Servicios',
    16.0,
    '16% de descuento en equipos de protección personal y sistemas de seguridad',
    '2024-02-20',
    '2025-12-31',
    1,
    1
),
-- Empresas adicionales activas pero no destacadas
(
    'Materiales Especializados SA',
    'Proveedor de materiales especializados para la industria manufacturera.',
    NULL,
    'https://materiales.mx',
    '+52 55 9012 3456',
    'ventas@materiales.mx',
    'Zona Industrial Sur',
    'Manufactura',
    8.0,
    '8% de descuento en materiales especializados',
    '2024-03-10',
    '2025-12-31',
    1,
    0
),
(
    'Servicios Administrativos Pro',
    'Empresa de servicios administrativos y contables para el sector empresarial.',
    NULL,
    'https://adminpro.mx',
    '+52 55 0123 4567',
    'info@adminpro.mx',
    'Centro de Negocios Polanco',
    'Servicios',
    14.0,
    '14% de descuento en servicios administrativos y contables',
    '2024-01-25',
    '2025-12-31',
    1,
    0
);

-- Verificar los datos insertados
SELECT 
    nombre_empresa,
    categoria,
    descuento,
    destacado,
    activo,
    fecha_inicio_convenio
FROM empresas_convenio 
ORDER BY destacado DESC, nombre_empresa ASC;
